### ISSUE TITLE
[Enhancement] Availability to load ZIP archives in dmc

### ISSUE THREAD

**Issue by habr-mms** [T-Systems-MMS/docker-management-container#72]
### Description

I'd like to be able to load GitHub releases that are only available as ZIP archives into the container via the binaries. The most important thing here is kubelogin (https://github.com/Azure/kubelogin)

**Comment by rndmh3ro** [comment]
We discussed this with @michaelamattes.

Since kubelogin is a simple go-binary, we think it is better suited directly in the [wakemeops-repository](https://github.com/upciti/wakemeops).

This way everybody who uses wakemeops can install it and the code in the DMC doesn't have to be changed.

There's documentation in the wakemeops-repository as well as in [ops2deb](https://github.com/upciti/ops2deb) on how to add kubelogin to wakemeops. If you need help creating a PR for it, feel free to reach out to me.
